#include <iostream>

/*
 * This program was generated by an AI to solve the Home Gardener problem.
 * It uses a system of linear equations to find the mixing proportions (M1, M2, M3)
 * that result in a balanced fertilizer with equal amounts of N, P, and K.
 */

using namespace std;

int main() {
    // Variable declarations for the NPK proportions of the three ingredients
    double n1, p1, k1, n2, p2, k2, n3, p3, k3;
    
    // Prompting the user to enter the NPK values for each ingredient
    // Note: The AI assumes the user will enter valid numbers
    cout << "Enter N, P, K for ingredient 1 (e.g., 0.07 0.01 0.02): ";
    cin >> n1 >> p1 >> k1;
    
    cout << "Enter N, P, K for ingredient 2: ";
    cin >> n2 >> p2 >> k2;
    
    cout << "Enter N, P, K for ingredient 3: ";
    cin >> n3 >> p3 >> k3;

    // Mixing proportions to be calculated
    double M1, M2, M3;

    /* 
     * Solving the system of equations using a simplified determinant-based approach.
     * The goal is to make total_N = total_P = total_K and M1 + M2 + M3 = 1.
     * This implementation uses Cramer's Rule for a 2x2 system after substituting M3 = 1 - M1 - M2.
     */
    
    // Calculate the determinant of the coefficient matrix
    double det = (n1 - n3) * (p2 - p3) - (n2 - n3) * (p1 - p3);
    
    // Calculate M1 and M2 using the target balanced value (assumed 1/3 for each element)
    // Warning: This logic assumes a balanced target of 1/3, which might not always be feasible.
    M1 = ((1.0/3.0 - n3) * (p2 - p3) - (1.0/3.0 - p3) * (n2 - n3)) / det;
    M2 = ((n1 - n3) * (1.0/3.0 - p3) - (p1 - p3) * (1.0/3.0 - n3)) / det;
    
    // M3 is the remaining proportion to ensure the sum is 1.0
    M3 = 1.0 - M1 - M2;

    // Output the resulting mixing proportions to the console
    cout << "--- Mixing Results ---" << endl;
    cout << "M1 (Ingredient 1): " << M1 << endl;
    cout << "M2 (Ingredient 2): " << M2 << endl;
    cout << "M3 (Ingredient 3): " << M3 << endl;
    
    return 0;
}
